/*
 * This source file was generated by the Gradle 'init' task
 */
package project1;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<Payable> accountsPayable = new ArrayList<>();
        accountsPayable.add(new SalariedEmployee("Alice Smith", "E001", 1200.00));
        accountsPayable.add(new Invoice("Widget-99", 5, 20.00));
        accountsPayable.add(new SalariedEmployee("Bob Jones", "E002", 1500.00));
        accountsPayable.add(new Invoice("Hammer-01", 2, 15.50));
        accountsPayable.add(new HourlyEmployee("Charlie Brown", "E003", 40, 15.00));

        for (Payable item : accountsPayable) {
            System.out.printf("Payment due: $%.2f%n", item.getPaymentAmount());
        }
    }
}
